### ISSUE TITLE
Exception comes when edit cron without schedule

### ISSUE THREAD

**Issue by Hector68** [kiwicommerce/magento2-cron-scheduler#10]
### Steps to reproduce
1. Create cron like this
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="index">
        <job name="xxx_queue" instance="MageAssist\Integration\Cron\Queue" method="execute">
            <config_path>xxx_integration/queue/cron_expression</config_path>
        </job>
    </group>
</config>

```
2.  Go to Systems - All cron jobs -> edit xxx_queue

3. Get error :
`Notice: Undefined index: schedule in /home/xxx/public_html/vendor/kiwicommerce/module-cron-scheduler/Ui/DataProvider/Form/CronJobDataProvider.php on line 83`

### Expected result
Posibility to edit cron or view details

### Actual result
![Error](http://joxi.ru/Vm6PZB9c4dERjA.png)

**Comment by kiwi-commerce** [comment]
Hi @Hector68 , Thank you for your report.
The issue has been fixed.

Related commit(s):
e104e05e5a1674f58ef5b17d7cdec99a1670e533
