### ISSUE TITLE
Missing version tag 1.0.6

### ISSUE THREAD

**Issue by lewisvoncken** [kiwicommerce/magento2-cron-scheduler#17]
Please create new version  because this commit is missing

https://github.com/kiwicommerce/magento2-cron-scheduler/commit/e104e05e5a1674f58ef5b17d7cdec99a1670e533#diff-6db7daed28db0d6d3d6c29b405ab4b9e

**Comment by kiwi-commerce** [comment]
@lewisvoncken We have released a new version 1.0.6.
Thank you.
