### ISSUE TITLE
Recurring Setup Script will not work for read only system

### ISSUE THREAD

**Issue by mhodge13** [kiwicommerce/magento2-cron-scheduler#2]
The recurring setup script in this module will not work on read only systems during deployments since it will try and copy the file over the other one and fail.

Example files that will get copied over are the observers:
https://github.com/kiwicommerce/magento2-cron-scheduler/tree/master/Observer

If different functionality is needed for different versions then it should check the version in the file and not try and copy a file over on setup:upgrade.

**Comment by kiwi-commerce** [comment]
Hi @mhodge13 , we are working on this use case. We will give you an update soon.
Thank you.

**Comment by kiwi-commerce** [comment]
Hi @mhodge13 . Thank you for your report.
The issue has been fixed for read only system
Related commit(s):

[be3188c49c82a6173a00af2d7ccfeadc3bb3ac1a](https://github.com/kiwicommerce/magento2-cron-scheduler/commit/be3188c49c82a6173a00af2d7ccfeadc3bb3ac1a)
[b62495bca5d0f2092aa27db353392d3f11751783](https://github.com/kiwicommerce/magento2-cron-scheduler/commit/b62495bca5d0f2092aa27db353392d3f11751783)
