### ISSUE TITLE
 Undefined index: config_path while editing cron job

### ISSUE THREAD

**Issue by killoff** [kiwicommerce/magento2-cron-scheduler#24]
### Title
Undefined index: config_path in module-cron-scheduler/Ui/DataProvider/Form/CronJobDataProvider.php on line 91

### Preconditions
Magento CLI 2.3.4
Module is installed and working properly

### Steps to reproduce
1. Go to Admin -> System ->  All cron jobs
2. Select any job and click "Edit" from jobs grid

### Expected result
Cron job form rendered

### Actual result
PHP notice 
Notice: Undefined index: config_path in vendor/kiwicommerce/module-cron-scheduler/Ui/DataProvider/Form/CronJobDataProvider.php on line 91

**Comment by umizoomi** [comment]
should be fixed if kiwicommerce accepts this pr https://github.com/kiwicommerce/magento2-cron-scheduler/pull/20

**Comment by kiwi-commerce** [comment]
Hello,  Thank you for your report.
The issue has been fixed in #20 by @dsitovs 

Related commit(s):
* 7a2e9bad8d3df721ed896142501ac3f4411a4a11

The fix will be available with the upcoming release.

Thank you.
