### ISSUE TITLE
How to get latest github version via composer?

### ISSUE THREAD

**Issue by Darkwolf81** [kiwicommerce/magento2-cron-scheduler#27]
Hello,
my problem is, when i install cron scheduler via composer, it takes the latest version from Magento Repository, 1.0.5. Only when i tell a version number like 1.0.7, it gets this from github. Problem may be that the package has the same name in both repository, and Magento 2 Repository has higher priority than gitgub.
So does anyone know how to get explicit the github version and updates via composer?

Best Regards,
Andreas

**Comment by kiwi-commerce** [comment]
Hello @Darkwolf81 ,

On the Magento marketplace and github, now there is a same version on the both platform that is 1.0.8.

Thank you.
