### ISSUE TITLE
Error in constructor ProcessCronQueueObserver

### ISSUE THREAD

**Issue by Tjitse-E** [kiwicommerce/magento2-cron-scheduler#3]
## Steps to reproduce
- Setup Magento 2.2.6 with PHP 7.1
- Install the `magento2-cron-scheduler`
- Run php bin/magento cron:run

## Expected result
The crons run

## Actual result
The cron's aren't running. Error:
> [23-Nov-2018 08:46:46 UTC] PHP Fatal error:  Uncaught TypeError: Argument 8 passed to Magento\Cron\Observer\ProcessCronQueueObserver::__construct() must be an instance of Magento\Framework\Stdlib\DateTime\DateTime, instance of Magento\Framework\Stdlib\DateTime\Timezone given, called in vendor/kiwicommerce/module-cron-scheduler/Observer/ProcessCronQueueObserver_2.1.php on line 65 and defined in vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:161
> Stack trace:
> #0 vendor/kiwicommerce/module-cron-scheduler/Observer/ProcessCronQueueObserver_2.1.php(65): Magento\Cron\Observer\ProcessCronQueueObserver->__construct(Object(Magento\Framework\App\ObjectManager), Object(Magento\Cron\Model\ScheduleFactory), Object(Magento\Framework\App\Cache\Proxy), Object(Magento\Cron\Model\Config), Object(Magento\Framework\App\Config), Object(Magento\Framework\App\Console\Request), Object(Magento\Framework\Shell), Object(Magento\Framework\Stdlib\Date in vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php on line 161

**Comment by kiwi-commerce** [comment]
Hi @Tjitse-E . Thank you for your report.
The issue has been fixed
Related commit(s):

[df176ff78b0071d7300b81df3987a051e1836d8c](https://github.com/kiwicommerce/magento2-cron-scheduler/commit/df176ff78b0071d7300b81df3987a051e1836d8c)
The fix will be available with the upcoming release.
