### ISSUE TITLE
No cron execution found

### ISSUE THREAD

**Issue by michelve** [kiwicommerce/magento2-cron-scheduler#4]
```
No cron execution found
```

what is this issue related to? it display on top of the page.

**Comment by kiwi-commerce** [comment]
Hi @michelve , this message indicates that your Magento cron job is not running.

Make sure it is running properly.
- Reference link: https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html

Please contact us on https://kiwicommerce.co.uk/get-in-touch/ if you still getting an issue.

Thank you.

**Comment by michelve** [comment]
i checked and cron jobs are working correctly

**Comment by stkrelax** [comment]
This might be because kiwicommerce_cronscheduler_status is set up in group index.
My additional Question to this Problem is why ? An why not in group default ?

**Comment by kiwi-commerce** [comment]
Hello @michelve ,

We are not getting this issue if the cron job runs correctly.

If you still get an issue, then please contact us on https://kiwicommerce.co.uk/get-in-touch/.

Thank you.

**Comment by rakibabu** [comment]
Having the same issue, cron is running properly and is successfully executed. But this extension is dropping this error message.
