### ISSUE TITLE
Module incompatible with Magento Config Dump

### ISSUE THREAD

**Issue by stkrelax** [kiwicommerce/magento2-cron-scheduler#7]
### Title
It is impossible to set Cronjob settings like is_active when the config was dumped.
### Preconditions
1. setup magento 2.3.1 and cron-scheduler
2. bin/magento app:config:dump

### Steps to reproduce
1. try to change is_active via admin or via command config set

### Expected result
1. is_active can be changed

### Actual result
1. in admin field is_active is diabled and console gives error

bin/magento config:set --lock-env crontab/group/jobs/jobcode/is_active 1
The "crontab/group/jobs/jobcode/is_active" path doesn't exist. Verify and try again.

 
![image](https://user-images.githubusercontent.com/48922246/59018475-43514a80-8846-11e9-80cc-27a11a287eb0.png)

**Comment by kiwi-commerce** [comment]
Hello @stkrelax ,

Please follow this link https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.html#config-cli-config-set and make sure you are using the correct command.

Thank you.

**Comment by stkrelax** [comment]
Hello kiwi-commerce 
as described in my Issue i did. I know the devdocs.

> bin/magento config:set --lock-env crontab/group/jobs/jobcode/is_active 1
> and got Error 
> 
> The "crontab/group/jobs/jobcode/is_active" path doesn't exist. Verify and try again.

please provide fix.
Thank You

**Comment by kiwi-commerce** [comment]
Hi @stkrelax , Thank you for your report.
The issue has been fixed.

Related commit(s):
7498a7ec94159790f2c0b12feaf71c413d896532
