### ISSUE TITLE
Element 'job': The attribute 'method' is required but missing.

### ISSUE THREAD

**Issue by jainmca4444** [kiwicommerce/magento2-cron-scheduler#8]
### Title

Element 'job': The attribute 'method' is required but missing.

### Preconditions
when we click on **All CRON job** or **Cron Scheduler list**  its throwing error on after redirection
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid Document 
Element 'job': The attribute 'method' is required but missing.
Line: 4

Element 'job': The attribute 'method' is required but missing.
Line: 7

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid Document 
Element 'job': The attribute 'method' is required but missing.
Line: 4

Element 'job': The attribute 'method' is required but missing.
Line: 7

<pre>#1 Magento\Framework\Config\Reader\Filesystem->read() called at [vendor/magento/framework/Config/Data.php:105]
#2 Magento\Framework\Config\Data->initData() called at [vendor/magento/framework/Config/Data.php:93]
#3 Magento\Framework\Config\Data->__construct() called at [vendor/magento/module-cron/Model/Config/Data.php:31]
#4 Magento\Cron\Model\Config\Data->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116]
#5 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]

### Steps to reproduce

1.  login into the admin section
2.  Go the System Setting and click on All Cron Job

**Comment by kiwi-commerce** [comment]
Hello @jainmca4444 ,

We can't reproduce the issue.

It seems like the third-party extension creating an issue from your side.
Try to disable third-party extensions that you think cause an issue and check if it resolves.

Thank you.
