### ISSUE TITLE
Cron time offset not correctly displayed in timeline

### ISSUE THREAD

**Issue by AntonEvers** [kiwicommerce/magento2-cron-scheduler#9]
### Title

The timeline entries are displayed as UTC, but the red line correctly marks the store timezone time.

### Preconditions

1. Set the timezone to Europe/Amsterdam
2. Truncate the cron schedule

### Steps to reproduce

1. Run a few cron jobs
2. Look at the Cron Scheduler Timeline

### Expected result

1. [Screenshots, logs or description]
![Screen Shot 2019-07-12 at 3 00 52 PM copy](https://user-images.githubusercontent.com/1489129/61130440-fac92480-a4b6-11e9-8282-8bc3e43ad301.png)

### Actual result

1. [Screenshots, logs or description]
![Screen Shot 2019-07-12 at 3 00 52 PM](https://user-images.githubusercontent.com/1489129/61130064-1c75dc00-a4b6-11e9-8eee-404760bfc53a.png)

**Comment by danielciornei** [comment]
@AntonEvers was curious about this issue and so far looks like it just affects timeline display, nothing functional as crons work as they should for me. 

i just added a +1 to the getNewDateForJs function in Block/Adminhtml/Schedule/Timeline.php  ( line 112)

` private function getNewDateForJs($date)
    {
        return "new Date(" . $this->datetime->date('Y,', $date) . ($this->datetime->date('m', $date) - 1) . $this->datetime->date(',d,H+1,i,s,0', $date) . ")";
    }`

Not exactly the best way, but seems to work

**Comment by AntonEvers** [comment]
@danielciornei yes it is purely visual. Not functional.

**Comment by kiwi-commerce** [comment]
Hi @AntonEvers , Thank you for your report.
The issue has been fixed.

Related commit(s):
f8f4c9c11f8b93042dbc5bfecc86a5d08696edb8
